name: Deploy Website
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Deploy to Ec2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/CFT
            git pull origin main
            sudo docker build -t sanjay-web .
            sudo docker stop sanjay-web-container || true
            sudo docker rm sanjay-web-container || true
            sudo docker run -d --name sanjay-web-container -p 8080:80 sanjay-web
            sudo cp "sanjay web.html" /var/www/html/index.html
            sudo systemctl restart apache2
            